### ISSUE TITLE
How do we view the project?

### ISSUE THREAD

**Issue by amazinigmech2418** [apex-os/APEX#1]
How will we be able to view the project so we can edit things?

**Comment by APEXCCPlymJoe** [comment]
Open it in Scratch Offline Editor.

**Comment by amazinigmech2418** [comment]
I don't have it.

**Comment by APEXCCPlymJoe** [comment]
Download it at scratch.mit.edu/download

**Comment by CStafford-14** [comment]
I got an alert for this. Anyways, you need the offline editor and the .sb2 file. We don't allow any ahead-of-time publishing for Apex.

**Comment by amazinigmech2418** [comment]
Could I use an unshared project? Also how do I connect to the apex cloud?

**Comment by APEXCCPlymJoe** [comment]
Yes you can. Also, you can use the APEX cloud in the offline editor. Please open a new issue if you have another question, though. @amazinigmech2418
